#!bin/bash
if [[ !(-d "$HOME/restore") ]]; then
    mkdir "$HOME/restore"
fi
backup=$(ls "$HOME" | grep -E "Backup-[0-9]{4}-[0-9]{2}-[0-9]{2}" | sort -n -t - -k 2,4 | tail -n 1)
if [[ -n "$HOME/$backup" ]]; then
    for filename in $(ls -A "$HOME/$backup" | grep -v -E ".[0-9]{4}-[0-9]{2}-[0-9]{2}$"); do
        cp "$HOME/$backup/$filename" "$HOME/restore"
    done
else
    echo "No backup was found"
fi
